export enum ErrorCode {
  // Business logic errors (E0 - E99)
  EMAIL_ALREADY_REGISTERED = 'E0',
  USER_NOT_FOUND = 'E1',
  INVALID_OTP = 'E2',
  EMAIL_ALREADY_VERIFIED = 'E3',
  RESET_TOKEN_MISSING = 'E4',
  INVALID_RESET_TOKEN_FORMAT = 'E5',
  RESET_TOKEN_USED = 'E6',
  INVALID_RESET_TOKEN = 'E7',
  INVALID_RESET_TOKEN_TYPE = 'E8',
  INVALID_CREDENTIALS = 'E9',
  EMAIL_UNVERIFIED = 'E10',
  SESSION_REVOKED = 'E11',
  SESSION_INACTIVE = 'E12',
  TOKEN_REUSE_DETECTED = 'E13',
  SESSION_NOT_FOUND = 'E14',
  FORBIDDEN_REVOKE = 'E15',
  ACCOUNT_SUSPENDED = 'E16',

  // Validation status error (E100)
  VALIDATION_FAILED = 'E100',
  // Validation field-specific errors (V0 - V99)
  EMAIL_INVALID = 'V0',
  PASSWORD_MIN_LENGTH = 'V1',
  PASSWORD_WEAK = 'V2',
  CONFIRM_PASSWORD_MISMATCH = 'V3',
  TERMS_REQUIRED = 'V4',
  PASSWORD_REQUIRED = 'V5',
  EMAIL_REQUIRED = 'V6',
  OTP_REQUIRED = 'V7',
  OTP_INVALID_FORMAT = 'V8',
}

export enum SuccessCode {
  // Success messages (S0 - S99)
  OTP_VERIFIED = 'S0',
  PASSWORD_RESET_SUCCESS = 'S1',
  VERIFICATION_EMAIL_SENT = 'S2',
  PASSWORD_RESET_EMAIL_SENT = 'S3',
  VERIFICATION_EMAIL_RESENT = 'S4',
  LOGOUT_SUCCESS = 'S5',
  REVOKE_SESSIONS_SUCCESS = 'S6',
}
